language: python

python:
  - "2.7"

before_install:
  - sudo apt-get install python-matplotlib

install:
  - pip install -r requirements.txt
  - python install.py

script:
  - python test.py

notifications:
  email: false